make this as dummy operator in cs 3.8
IBM/ibm-monitoring-prometheus-operator-ext pull request #79
Opened 2021-05-19 07:28 UTC by Tirumalavasa

Code prior to this dummy operator is present in `master-orig-cs39` branch

2021-05-19 08:43 UTC, pgodowski commented
please have a review with Tamilu too. Please before also create branch/tag/release before this change gets merged.

2021-05-19 08:59 UTC, pgodowski requested changes

2021-05-19 08:59 UTC, pgodowski commented on pkg/controller/prometheusext/prometheusext_controller.go
> -	reconsiler := reconsiler.Reconsiler{
given that it's dummy operator now, shall we revisit the resource request/limits for the operator, to lower it down?

2021-05-20 13:34 UTC, pgodowski commented
/lgtm

2021-05-20 13:34 UTC, pgodowski approved these changes

2021-05-21 06:04 UTC, Tirumalavasa commented on pkg/controller/prometheusext/prometheusext_controller.go
> -	reconsiler := reconsiler.Reconsiler{
Sure, i will adjust these resources in the csv in the upcoming PR

2021-05-21 06:04 UTC, merged